### ISSUE TITLE
Pass extracted route parameters to agents.

### ISSUE THREAD

**Issue by horned-sphere** [swimos/swim-rust#515]
Extend `swim_api::agent::Agent` to allow a map of the extracted route parameters to be passed to the agent in addition to the route URI. This should also be exposed via a `HandlerAction` in the `swim_agent` API.

**Comment by SirCipher** [comment]
Does this still need implementing given that `get_parameter` exists?

**Comment by horned-sphere** [comment]
> Does this still need implementing given that `get_parameter` exists?

No, this one is done.
