### ISSUE TITLE
Add granular support for TLS on the server

### ISSUE THREAD

**Issue by DobromirM** [swimos/swim-rust#604]
Currently `ServerBuilder` can enable TLS support using the `add_tls_support(mut self, config: TlsConfig)` method, however the `TlsConfig` requires both a `ClientConfig` and a `ServerConfig`.

It should be possible to create servers that can open server downlinks with TLS, without requiring them to have TLS support themselves.

**Comment by horned-sphere** [comment]
It should probably be the case that _outgoing_ TLS is just there by default.
